### ISSUE TITLE
training  code

### ISSUE THREAD

**Issue by fangwudi** [blackfeather-wang/GFNet-Pytorch#2]
great job~ waitting for training code

**Comment by blackfeather-wang** [comment]
Thank you for focusing on our work! We are now working on polishing the training code, and it will be updated in no more than 2 weeks.

**Comment by xjtuwh** [comment]
> Thank you for focusing on our work! We are now working on polishing the training code, and it will be updated in no more than 2 weeks.

Where is the training code?

**Comment by blackfeather-wang** [comment]
The training code, as well as the initializations and stage-1/2 checkpoints, have been released. Currently, we include the checkpoints of ResNet and MobileNet-V3 to exactly reproduce our training process. However, we will update other models as soon as we can. Feel free to contact me if you have any question :)

**Comment by blackfeather-wang** [comment]
> > Thank you for focusing on our work! We are now working on polishing the training code, and it will be updated in no more than 2 weeks.
> 
> Where is the training code?

I apologize for the delay. The training code has been released.
