### ISSUE TITLE
very nice work!

### ISSUE THREAD

**Issue by ljwwwiop** [blackfeather-wang/GFNet-Pytorch#3]
very great work,great paper ,l have a question just is for example,in first layer Classifier fc,l know fc is RNN,but l dont know what is the fc to next fc pass through h1C,thanks,vevy nice!

**Comment by blackfeather-wang** [comment]
> very great work,great paper ,l have a question just is for example,in first layer Classifier fc,l know fc is RNN,but l dont know what is the fc to next fc pass through h1C,thanks,vevy nice!

Thank you for your attention. The hidden state is stored inside the fc when the sequential decision process goes on.
