### ISSUE TITLE
请问为什么不训练某些特定prime model

### ISSUE THREAD

**Issue by darknli** [blackfeather-wang/GFNet-Pytorch#4]
![image](https://user-images.githubusercontent.com/45683576/104113098-4c16d600-5331-11eb-8d2b-2c33f66be36c.png)

您好，非常感谢您代码的分享，我想训练一个轻量级的模型，比如mobilenetv3_small_100，但并没有提供预训练模型。如果prime model因为with torch.no_grad()而无法更新网络，效果应该会受到影响。期待您的回复！

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work! 
(To make more persons understand this issue, we kindly suggest that we may communicate in English.)

As we mentioned in the paper, we find it helpful to first finetune the global encoder (model_prime) on small inputs (e.g., 96x96), and then fix it when training GFNet (based on MobileNet-V3). As this repo is released to reproduce the results in the paper, we follow exactly the same setting as our paper. Indeed, we do not provide the pre-trained mobilenetv3_small_100 as we did not conduct experiments with it.

For this issue, there may be two solutions:
1. Finetuning the ImageNet pre-trained mobilenetv3_small_100 with small inputs as we do (we recommend this repo: https://github.com/rwightman/pytorch-image-models). This may take a bit long time, but will lead to state-of-the-art performance.
2. Directly initializing the global encoder (model_prime) with ImageNet pre-trained mobilenetv3_small_100, and train it together with other parts of GFNet. This may slightly hurt the performance (mainly for the glance step).

**Comment by darknli** [comment]
Thank you，the answer helped me a lot.
